---
- name: Restart docker
  ansible.builtin.service:
    name: "{{ docker.service_name }}"
    state: restarted

- name: Reload docker
  ansible.builtin.service:
    name: "{{ docker.service_name }}"
    state: reloaded
